# Generated by Django 2.2.16 on 2021-10-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211015_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='image',
            field=models.SlugField(max_length=500, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='link',
            field=models.SlugField(max_length=500, verbose_name='Ссылка'),
        ),
    ]
